import {JSX} from 'react'
import Markdown from 'react-markdown'
import rehypeRaw from 'rehype-raw'
import remarkGfm from 'remark-gfm'

import './block.scss'

interface BlockProps {
  blockInfo: string
}

export const Block = ({blockInfo}: BlockProps): JSX.Element => {
  let markdown = <></>
  if (blockInfo) {
    markdown = (
      <Markdown
        remarkPlugins={[remarkGfm]}
        rehypePlugins={[rehypeRaw]}
        className='markdown'
        components={{
          // Fixed uncontrolled input warning generated by planToMarkdown.tsx
          // for textual plan preview
          // Override checkbox rendering to make them controlled components
          input: ({node, checked, ref, ...props}) => {
            if (props.type === 'checkbox') {
              return (
                <input
                  type='checkbox'
                  checked={checked || false}
                  onChange={() => {}} // read-only, no-op handler
                  disabled
                />
              )
            }
            // non-checkbox inputs, pass all props
            return <input {...props} />
          },
        }}
      >
        {blockInfo}
      </Markdown>
    )
  }

  return <div className='block-container'>{markdown}</div>
}
